on: [workflow_call]
name: "Check"
permissions: {}

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x --source-path=src -e SC1091 -e SC2001 -e SC2034 -e SC2064 -e SC2317 -e SC2153
      - 
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.2.0
        with:
          dockerfile: Dockerfile
          ignore: DL3008,DL3003,DL3035,DL3059
          failure-threshold: warning
